apiVersion: v1
kind: Service
metadata:
  name: fraud-backend
  namespace: fraud-detection
spec:
  selector:
    app: fraud-backend
  ports:
    - port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-backend
  namespace: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-backend
  template:
    metadata:
      labels:
        app: fraud-backend
    spec:
      containers:
        - name: backend
          image: fraud-backend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://fraud-postgres:5432/fraud_detection"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "fraud-kafka:9092"
            - name: ML_SERVICE_URL
              value: "http://fraud-ml:8000"
            - name: ML_SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ml-secret
                  key: ML_API_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "896Mi"
              cpu: "1000m"