apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-ml-models
  namespace: fraud-detection
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-ml
  namespace: fraud-detection
spec:
  selector:
    app: fraud-ml
  ports:
    - port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-ml
  namespace: fraud-detection
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fraud-ml
  template:
    metadata:
      labels:
        app: fraud-ml
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: fix-perms
          image: fraud-ml:1.0
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chown -R 1001:1001 /ml/models"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: models
              mountPath: /ml/models
      containers:
        - name: ml
          image: fraud-ml:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: models
              mountPath: /ml/models
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              ephemeral-storage: "512Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              ephemeral-storage: "1Gi"
              cpu: "500m"
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: fraud-ml-models